name: Niflheim
version: '0.15'
main: fr.hyu.Main
api-version: '1.20'
commands:
  gma:
  gmc:
  gms:
  gmsp:
  setspawn:
  spawn:
  permstest:
  test:
  niflheimEconomy:
  niflheimMMO:
  niflheimPerms:
  xp:
  chatcolor:
  patchnote:

